<?php

namespace Cant\Phase\Me\Models;

use Rhubarb\Stem\Schema\SolutionSchema;

class PhasedSolutionSchema extends SolutionSchema
{
    public static function registerSchema($schemaName, $schemaClass)
    {
        parent::registerSchema($schemaName, $schemaClass); // TODO: Change the autogenerated stub
    }

}